import os,csv,operator,itertools

origin = []
result = []
with open("count_info_with_score_v4.csv", 'rb') as read_file:
    read_in = csv.reader(read_file)
    for row in itertools.islice(read_in, 1, None):
        origin.append(row)

originlength = -1
while originlength < 166:
    originlength += 1
    group = origin[originlength*4:originlength*4+4]
    i = 0
    while i < 38:
        i += 1
        if i == 0 or i == 4 or i == 5:
            continue
        group[0][i] = float(group[0][i])
        group[1][i] = float(group[1][i])
        group[2][i] = float(group[2][i])
        group[3][i] = float(group[3][i])
        
    item = []
    item.append(group[0][0])
    tmp_a = group[0][1]+group[1][1]+group[2][1]+group[3][1]
    item.append(tmp_a)
    tmp_b = group[0][2]+group[1][2]+group[2][2]+group[3][2]
    item.append(tmp_b)
    item.append((tmp_a*1.0) / (tmp_b*1.0))
    tmp_c = group[0][6]+group[1][6]+group[2][6]+group[3][6]
    item.append(tmp_c)
    tmp_d = group[0][8]+group[1][8]+group[2][8]+group[3][8]
    item.append(tmp_d)
    tmp_e = group[0][7]+group[1][7]+group[2][7]+group[3][7]
    item.append(tmp_e)
    item.append((tmp_c*1.0) / tmp_d)
    item.append((tmp_e*1.0) / tmp_d)
    item.append((tmp_c*1.0) / tmp_e)
    item.append(group[0][12])
    item.append(group[0][21])
    item.append(group[0][30])
    item.append(group[1][12])
    item.append(group[1][21])
    item.append(group[1][30])
    item.append(group[2][12])
    item.append(group[2][21])
    item.append(group[2][30])
    item.append(group[3][12])
    item.append(group[3][21])
    item.append(group[3][30])
    item.append(group[0][14])
    item.append(group[0][23])
    item.append(group[0][32])
    item.append(group[1][14])
    item.append(group[1][23])
    item.append(group[1][32])
    item.append(group[2][14])
    item.append(group[2][23])
    item.append(group[2][32])
    item.append(group[3][14])
    item.append(group[3][23])
    item.append(group[3][32])
    item.append(group[0][13])
    item.append(group[0][22])
    item.append(group[0][31])
    item.append(group[1][13])
    item.append(group[1][22])
    item.append(group[1][31])
    item.append(group[2][13])
    item.append(group[2][22])
    item.append(group[2][31])
    item.append(group[3][13])
    item.append(group[3][22])
    item.append(group[3][31])
    item.append(group[0][16])
    item.append(group[0][25])
    item.append(group[0][34])
    item.append(group[1][16])
    item.append(group[1][25])
    item.append(group[1][34])
    item.append(group[2][16])
    item.append(group[2][25])
    item.append(group[2][34])
    item.append(group[3][16])
    item.append(group[3][25])
    item.append(group[3][34])
    item.append(group[0][15])
    item.append(group[0][24])
    item.append(group[0][33])
    item.append(group[1][15])
    item.append(group[1][24])
    item.append(group[1][33])
    item.append(group[2][15])
    item.append(group[2][24])
    item.append(group[2][33])
    item.append(group[3][15])
    item.append(group[3][24])
    item.append(group[3][33])
    item.append(group[0][17])
    item.append(group[0][26])
    item.append(group[0][35])
    item.append(group[1][17])
    item.append(group[1][26])
    item.append(group[1][35])
    item.append(group[2][17])
    item.append(group[2][26])
    item.append(group[2][35])
    item.append(group[3][17])
    item.append(group[3][26])
    item.append(group[3][35])
    item.append(group[0][18])
    item.append(group[0][27])
    item.append(group[0][36])
    item.append(group[1][18])
    item.append(group[1][27])
    item.append(group[1][36])
    item.append(group[2][18])
    item.append(group[2][27])
    item.append(group[2][36])
    item.append(group[3][18])
    item.append(group[3][27])
    item.append(group[3][36])
    item.append(group[0][20])
    item.append(group[0][29])
    item.append(group[0][38])
    item.append(group[1][20])
    item.append(group[1][29])
    item.append(group[1][38])
    item.append(group[2][20])
    item.append(group[2][29])
    item.append(group[2][38])
    item.append(group[3][20])
    item.append(group[3][29])
    item.append(group[3][38])
    item.append(group[0][19])
    item.append(group[0][28])
    item.append(group[0][37])
    item.append(group[1][19])
    item.append(group[1][28])
    item.append(group[1][37])
    item.append(group[2][19])
    item.append(group[2][28])
    item.append(group[2][37])
    item.append(group[3][19])
    item.append(group[3][28])
    item.append(group[3][37])
    
    result.append(item)
    
countInfoWithScore = file('_fifth_.csv', 'wb')
fileObject = csv.writer(countInfoWithScore, dialect='excel')
fileObject.writerows(result)
countInfoWithScore.close()
print "complete"